export default [
  { name: "Frontend Developer", value: "Frontend Developer" },
  { name: "Backend Developer", value: "Backend Developer" },
  { name: "Fullstack Developer", value: "Fullstack Developer" },
  { name: "Mobile Developer", value: "Mobile Developer" },
  { name: "Data Scientist", value: "Data Scientist" },
  { name: "Data Engineer", value: "Data Engineer" },
  { name: "Machine Learning Engineer", value: "Machine Learning Engineer" },
  { name: "AI Engineer", value: "AI Engineer" },
  { name: "Blockchain Developer", value: "Blockchain Developer" },
  { name: "Security Engineer", value: "Security Engineer" },
  { name: "UI/UX Designer", value: "UI/UX Designer" },
  { name: "Product Manager", value: "Product Manager" },
  { name: "Project Manager", value: "Project Manager" },
  { name: "DevOps Engineer", value: "DevOps Engineer" },
  { name: "QA Engineer", value: "QA Engineer" },
];
